### ISSUE TITLE
هدر صفحه اصلی

### ISSUE THREAD

**Issue by haghshenasdev** [MJbidram/charity#3]
نوار بالای صفحه صلی که بعد از اسکرول کردن ظاهر می شود به جای رنگ ثابت از گردینت تم استفاده شود.

**Comment by MJbidram** [comment]
این نوار فقط پارامتر color دریافت میکنه . احتمالا برای درست کردنش باید یه پکیج نصب کنم.
به نظر خودم که اگه تک رنگ باشه قشنگ تر میشه  ولی اگه میخوای گردینت باشه سعیمو میکنم درستش کنم
